export const pendingTaks = [
  {
    taskId: "38e914e5-a9a1-11eb-921b-dac0a6c2b73f",
    taskName: "CDCP Task",
    created_date: "2021-04-30T10:45:47.456+00:00",
    updated_date: null,
    taskDefKey: "CDCP",
    taskData: {
      employeeName: "Employee_3",
      empDeptName: "IB CM&A Real Estate APAC",
      purpose: "PER",
      employeePID: "EMP_3",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "CDCP",
      destinationId: 538954.0,
      travelRequestId: 496396.0,
      rowOrder: 1.0,
      empDeptCode: "UARA3",
      division: "IB",
      employeeType: "Private",
      aging: "4.0",
      employeePhnNbr: "+44 20 7883 2226",
      status: "Awaiting CDCP Response",
    },
  },
  {
    taskId: "38ee1e10-a9a1-11eb-921b-dac0a6c2b73f",
    taskName: "CDCP Task",
    created_date: "2021-04-30T10:45:47.489+00:00",
    updated_date: null,
    taskDefKey: "CDCP",
    taskData: {
      employeeName: "Employee_4",
      empDeptName: "EQD Flow Sales NA",
      purpose: "PER",
      employeePID: "EMP_4",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "CDCP",
      travelRequestId: 501860.0,
      destinationId: 545919.0,
      rowOrder: 1.0,
      empDeptCode: "UUAC133",
      division: "IB",
      employeeType: "Private",
      aging: "3.0",
      employeePhnNbr: "+44 20 7883 2227",
      status: "Awaiting CDCP Response",
    },
  },
  {
    taskId: "38f1517b-a9a1-11eb-921b-dac0a6c2b73f",
    taskName: "COO Task",
    created_date: "2021-04-30T10:45:47.510+00:00",
    updated_date: null,
    taskDefKey: "COO",
    taskData: {
      employeeName: "Employee_5",
      empDeptName: "IB CM&A Real Estate APAC",
      purpose: "PER",
      employeePID: "EMP_5",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "COO",
      rowOrder: 1.0,
      destinationId: 538954.0,
      travelRequestId: 496396.0,
      empDeptCode: "UARA3",
      division: "IB",
      employeeType: "Private",
      aging: "4.0",
      employeePhnNbr: "+44 20 7883 2228",
      status: "Pending for COO Review",
    },
  },
  {
    taskId: "44e1f5b0-a902-11eb-90de-dac0a6c2b73f",
    taskName: "CDCP Task",
    created_date: "2021-04-29T15:47:57.558+00:00",
    updated_date: null,
    taskDefKey: "formTask1",
    taskData: {
      employeeName: "Employee_3",
      empDeptName: "IB CM&A Real Estate APAC",
      purpose: "PER",
      employeePID: "EMP_3",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "CDCP",
      travelRequestId: 496396.0,
      destinationId: 538954.0,
      rowOrder: 1.0,
      empDeptCode: "UARA3",
      division: "IB",
      employeeType: "Private",
      aging: 4.0,
      employeePhnNbr: "+44 20 7883 2226",
      status: "Awaiting CDCP Response",
    },
  },
  {
    taskId: "44eacf6b-a902-11eb-90de-dac0a6c2b73f",
    taskName: "CDCP Task",
    created_date: "2021-04-29T15:47:57.620+00:00",
    updated_date: null,
    taskDefKey: "formTask1",
    taskData: {
      employeeName: "Employee_4",
      empDeptName: "EQD Flow Sales NA",
      purpose: "PER",
      employeePID: "EMP_4",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "CDCP",
      destinationId: 545919.0,
      rowOrder: 1.0,
      travelRequestId: 501860.0,
      empDeptCode: "UUAC133",
      division: "IB",
      employeeType: "Private",
      aging: 3.0,
      employeePhnNbr: "+44 20 7883 2227",
      status: "Awaiting CDCP Response",
    },
  },
  {
    taskId: "f2d462f5-a913-11eb-998f-dac0a6c2b73f",
    taskName: "COO Task",
    created_date: "2021-04-29T17:54:30.841+00:00",
    updated_date: null,
    taskDefKey: "COO",
    taskData: {
      employeeName: "Employee_7",
      empDeptName: "EQD Flow Sales APAC",
      purpose: "PER",
      employeePID: "EMP_7",
      initiator: null,
      workPlaceCountry: "United Kingdom",
      nextTaskOutcome: "COO",
      travelRequestId: 496396.0,
      destinationId: 538954.0,
      rowOrder: 1.0,
      empDeptCode: "UARA3",
      division: "IB",
      employeeType: "Private",
      aging: "4.0",
      employeePhnNbr: "+44 20 7883 2230",
      status: "Pending for COO Review",
    },
  },
];

export const summaryData = [
  {
    status: "Closed",
    Count: "30",
  },
  {
    status: "Pending for COO Review",
    Count: "15",
  },
  {
    status: "Awaiting CDCP Response",
    Count: "21",
  },

  {
    status: "Reject",
    Count: "5",
  },
  {
    status: "Approve",
    Count: "4",
  },
  {
    status: "Records Updated - FCA Certified",
    Count: "2",
  },
];
